# Generated by Django 3.0.4 on 2020-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServisClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mikesz', models.BooleanField(default=False)),
                ('cash_reg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other', models.TextField(blank=True)),
            ],
        ),
    ]
