# Generated by Django 3.0.4 on 2020-03-10 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_made', models.DateField(blank=True)),
                ('other', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_base.ServisClient')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('servis_range', models.TextField()),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('other', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_base.Bike')),
            ],
        ),
    ]
