# Generated by Django 3.0.4 on 2020-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_base', '0002_bike_comments_servis'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
